### ISSUE TITLE
Update submodule in PreAndPostProcessingScripts following support for reading namelist and streams files

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Analysis#28]
Following completion of recent improvements to generalize usage of MPAS-Analysis we will need to update the submodule for inclusion in ACME (https://github.com/ACME-Climate/PreAndPostProcessingScripts).  The goal of this issue is to document PRs that we want to make sure are included as part of this update process.

A partial list of improvements (issues / PRs) to be included:
- [x] #26 (generalized run analysis)
- [x] #27 (namelist / streams file interfaces)
- [x] #38 (read configuration from namelist files and stream file names from streams file)
- [x] #45 (support time-series analysis over a subset of the output data)

**Comment by pwolfram** [comment]
@milenaveneziani, do you think we are missing anything on the above list?

**Comment by pwolfram** [comment]
Thanks for the updates @milenaveneziani  and @xylar in the above list.

**Comment by pwolfram** [comment]
@milenaveneziani and @xylar, following merging of #55, my understanding is that we can update `PreAndPostProcessingScripts` and close this issue, correct?

**Comment by xylar** [comment]
That's my understanding as well.

**Comment by pwolfram** [comment]
Note, I believe that we should be able to close this issue following resolution of https://github.com/ACME-Climate/PreAndPostProcessingScripts/pull/24.

**Comment by xylar** [comment]
Until that PR is actually merged, I think this should stay open.

**Comment by pwolfram** [comment]
Agreed, issues should only be closed after rectifying PRs are merged.

**Comment by milenaveneziani** [comment]
yes, we should be close to fulfill ACME-Climate/PreAndPostProcessingScripts#24.

**Comment by milenaveneziani** [comment]
ACME-Climate/PreAndPostProcessingScripts#24 was fulfilled, so closing this now.
