### ISSUE TITLE
Checklist for v0.8.0

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#303]
To do:

- [ ] Add support for online MOC

- [ ] Break MOC into separate tasks for climatology and time series

- [ ] Support comparison with ref in MOC time series

- [ ] Make line colors consistent for main, ref, v0 and obs in time series and MHT plots

- [ ] Task for MLD and KE comparison with SOSE

- [ ] ...

**Comment by milenaveneziani** [comment]
@xylar: I meant to add the online MOC script, only that will probably be after OS.

**Comment by vanroekel** [comment]
@xylar and @milenaveneziani I just posted a new version of my python notebook for the online MOC am analysis.  Not sure if it will help for this task, but it is in the MPAS-QuickViz repo if you'd like to take a look.

**Comment by milenaveneziani** [comment]
Thanks @vanroekel: that will certainly help.

**Comment by xylar** [comment]
I made issues for each item on the check list above and am closing this issue, since not all of these items will be included in v 1.0.0.
