### ISSUE TITLE
Summary of key analysis tasks

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Analysis#32]
**Key tasks to be completed include:**
- [X] Add namelist and streams file interfaces (#27)
- [x] Ingest namelist and streams file data, e.g., don't hard code paths to model output but instead get path from streams file (#20 and #38)
- [x] Support time-series analysis over a subset of the output data (#45)
- [x] Generalize use of variable names to support multiple versions of ACME (e.g., account for changing of variable names under different versions) (#20)
- [x] Update submodule in PreAndPostProcessingScripts following support for reading namelist and streams files (#28)
- [x] mpas_xarray needs to support different approaches to specification of time output for AMs (#33, #38, others?)
- [x] Add a check on whether the needed AM for the analysis was turned on. For example, we will always need timeSeriesStats, but of course we'll want specific am's for metrics such as the OHC, MOC, etc. (#58)
- [x] Deal with problem of too many open files for xarray (https://github.com/MPAS-Dev/MPAS-Analysis/issues/49)
- [ ] See if we can generate a html interface for better sharing/visualization of MPAS standalone results
- [x] Make sure we support changes in MPAS-SI timeSeriesStats before they are merged in ACME
- [x] Add MHT script
- [x] Add MOC script (for offline calculation only for the moment)
- [x] Make sure analysis scripts do not rely on mesh info present in input files (#30)

**Lower priority for now:**
- [x] Generalize interpolation module (to include ncremap and possibly another method)
- [x] Add compute-climatologies module
- [ ] Generalize modelvsobs for ocean and sea-ice (#31)
- [x] Do not re-compute climatologies or do not interpolate if these actions have already been done (files exist)
- [x] Perhaps at some point we should save time series to file (especially at high-res and when using many output files)
- [ ] Add capability to compare time series with results from a different simulation
- [ ] Improvement of documentation (#3, #9, #11)
- [ ] General clean up (#18, #43, #19, #30)
- [x] Add changes when short-term archiving will be adopted in ACME

**Comment by pwolfram** [comment]
@xylar and @milenaveneziani, we need to depreciate https://github.com/pwolfram/mpas_xarray because we really should have that in this analysis repo.  Before this is done, I think we need to have the capability to install MPAS-Analysis as a package, e.g., via pip.  Do you all concur?  If so, it can be added to the list above.

**Comment by xylar** [comment]
@pwolfram, I don't have a strong opinion either way about whether MPAS-Analysis needs to be a package.  Our ACME workflow doesn't need this capability but maybe you have workflows that expect `mpas_xarray` to be available via pip.

For my own development, I have found it to be a bit of a pain to have POPSICLES set up as a package.  Each time I modify the code, I have to re-install the package (and I sometimes have to uninstall it first with an old setup to make sure I don't have old files lying around).  A setup more like we currently have in ACME or similar to CIME would better facilitate development.  So I am opposed to *requiring* MPAS-Analysis to be installed as a package but I don't have a problem with supporting the option.

**Comment by pwolfram** [comment]
@xylar, we previously decided on *requiring* MPAS-Analysis to be installed as a package so at this point we are committed to doing this eventually.  There are downsides as you detail.  If you have any additional ideas on how to best mitigate the downsides that you list that would be really helpful.  However, the upside is that we will be better able to interface with a broader community by supporting this option long term.

**Comment by milenaveneziani** [comment]
@pwolfram: is this a list of high-priority tasks for MPAS-Analysis, in order to make the package compatible with ACME alpha8 and 9?

**Comment by pwolfram** [comment]
@milenaveneziani, I believe so.  We may be able to put off #33 depending upon alpha9.  Does this sound reasonable to you?  Please edit the list if I missed something or there is an extraneous item

**Comment by milenaveneziani** [comment]
@pwolfram: I have added all the things I can think of for now. This list does not include all the possible other scripts we can think of writing (hovmoeller diagrams, transects, other time series, etc), but just the important elements that we need to have in place to satisfy most of our requirements.
One comment about the 'Update submodule for ACME' item: this will be an on-going task, so perhaps we do not need to have it as an issue or on the list?

**Comment by xylar** [comment]
@milenaveneziani and @pwolfram, I think #28 (and check-list item "Update submodule in PreAndPostProcessingScripts") should be made renamed to be specific to the list of tasks that needs to be achieved before that update.  I'm going to go ahead and rename them so they are more meaningful.

**Comment by milenaveneziani** [comment]
@pwolfram, @xylar: I have updated the list and added more items to it, also following our email exchange. I realize this has become more of a laundry list at this point, but I think it is nice to put things down in one single place.
For the next month or so, I think we should prioritize the first 5 unchecked boxes: do you agree?

**Comment by pwolfram** [comment]
@milenaveneziani, just to be clear, can we please clarify the high-priority needs right now?  Can you please copy/paste them in a reply just so that this is crystal clear?  The reason I ask is because we've recently checked some of the boxes above and I just want to make sure we are all on the same page and are completing the work we need for the analysis.

**Comment by pwolfram** [comment]
Note, I checked off the box `mpas_xarray needs to support different approaches to specification of time output for AMs` above because I would say that we have this needed support now and the cited issues / PRs are closed / merged.

**Comment by milenaveneziani** [comment]
We now have a Confluence page and various Jira tasks that include the items in this list. @pwolfram: I would probably close this issue.
