### ISSUE TITLE
Checklist for v1.0 release

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#347]
To do before the release:
- [x] add following data to public server/repo:
   - [x] observations that only need an acknowledgment: UCAR SST, ERSv4 SST we use for the Nino index, NASA SSS, Argo (both the Scripps and the Roemmich data sets), Trenberth data, AVISO SSH, SOSE, NASA SSMI (sea-ice concentration), NASA IceSat (sea-ice thickness), sea-ice area time series, PIOMAS sea-ice volume time series
   - [x] license information or other terms of use and a bibtex file for each data set #367 
   - [x] pre-generated mapping files for the EC60to30v3 and the oRRS30to10 grids
   - [x] the MOC mask files for the EC60to30v3 and the oRRS30to10 grids
- [x] script to download data from public repo (one time donwload for now)
- [x] update documentation and obs database
- [x] MPAS-Analysis support for online MOC
- [x] Plotting of transects #327

**Comment by milenaveneziani** [comment]
@xylar: thanks for making this list. I am removing the open bullet 'cause I'd be already thrilled if we could complete the first 3 tasks by the release of v1..

Here is an idea about the observations folder: considering that the amount of processed data we will be releasing *and* the amount of data that users would have to process on their own for v1 is not that large, could we have the observations folder as part of the MPAS-Analysis structure for now? This would save work on figuring out how to get to the public server, and how to retrieve data from it if the data is not locally available.

**Comment by xylar** [comment]
@milenaveneziani, I'm not sure what you mean by "could we have the observations folder as part of the MPAS-Anlaysis structure for now".  If you mean, could we add the observations to the code repo, I think the answer is definitely no.  I think we are talking about many GB of data.  That's far too large to go directly in the MPAS-Analysis repo.  We generally hesitate to put files that are even a few tens of MB in the code repo because it makes the process of checking out, branching and updating the code quite a bit slower.  Plus, GitHub simply doesn't allow large files.  I definitely think we need a different repo.

**Comment by milenaveneziani** [comment]
ok, forget what I said above.
I am going to use this issue to detail the tasks needed for the release.

**Comment by milenaveneziani** [comment]
@xylar: I have updated the to-do list above with more details about the observational data sets. I still left a couple of questions open, but mostly it should be OK. Let me know if you have comments or questions.

**Comment by xylar** [comment]
Okay, I don't plan on making any new pull requests until the v1.0 release.  I will make a draft message for the release below.

**Comment by xylar** [comment]
Done!
