### ISSUE TITLE
Version 1.1

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#481]
Checklist for the release:

- [x] Entry point - #477 
- [x] Python 3.7 - #479 
- [x] Remove depricated functions - #480 
- [x] Updates to timeSeriesAntarcticMelt and generating masks #482, #483  
- [x] Fix artifacts in BGC obs plots #486 
- [x] Enhance "error bars" for observations in Antarctic melt time series plots #489
- [x] Double check the docs, including authors list, add image for BGC run #485 
- [x] Double check once again all observation and mapping files on the supported machines
- [x] Check `generate` line in template config files to add `no_*` options for not-applicable analyses (like BGC, landice, etc) #485 
- [x] Update version number to 1.1 - #477 

Here's a draft release message for v1.1:

Highlights include analysis of surface biogeochemistry,  eddy kinetic energy and iceberg concentration as well as enhancement of transect plots.

### Major Enhancements
* Lat and lon axes for transect plots #437
* Task to plot iceberg concentration #320
* Task for surface climatology maps of ocean biogeochemistry fields #433
* Transect contour plots #450
* Eddy Kinetic Energy (EKE) climatology analysis #447 

### Minor Enhancements
* Added a utility for making an MPAS to Antarctic mapping file #446
* Updated the location, depth and seasons for SOSE transects #462
* Added climatologyMapBGC to docs #471
* Switched to using an entry point for the mpas_analysis package #477
* Added a subtask for computing region masks on the fly #482 
* Split TimeSeriesAntarcticMelt into multiple subtasks #483
* Enhance "error bars" for observations in Antarctic melt time series plots #489 
* Break the MOC into several subtasks #487

### Minor clean-up
* Disabled HDF5 locking in example job scripts #443
* Updated license file #444, #448
* Refactored BGC so it is one task, not one per field #453
* Updated the list of public observations #456
* Removed depricated inplace arg to xarray ds rename calls #480
* Clean up documentation #485 

### Bug fixes
* Bug fix in climatology anomalyRefYear #442
* Bug fix in interpolating transect segments #439
* Fixed error reporting on tasks #449
* Updated observations XML for EKE #454
* Fixed some errors and warnings that come up during CI #465
* Fixed Read The Docs and updated to python 3.6  #466, #467, #469
* Fixed detecting periodic lat/lon descriptors #475
* Explicitly set colormap type (indexed or continuous) in config options #473
* Fixed CI under python 2 #478
* Update to CI to python 3.7 #479
* Add periodic image to BGC obs data #486 
* Catches zero arguments #491

**Comment by xylar** [comment]
@milenaveneziani, please add anything you would like to the check list.  I think we're due (maybe overdue) for another release.

**Comment by xylar** [comment]
Thanks for adding to the checklist!

**Comment by xylar** [comment]
@milenaveneziani, I think everything is ready for the 1.1 release except:
* merging #487 if we want to include it
* updating `diagnostics` on all of the supported machines (including LANL IC)

I think you should be the one to update the supported machines because permissions are set up for you to update at the moment, and you have a good sense of how that should be done.

What do you think, should we include #487?  If so, I'll wait for you to have time to test it.

**Comment by milenaveneziani** [comment]
@xylar, I would include #487 in version 1.1. I'd like to get testing and checking of the `diagnostics` folder done before the Thanksgiving break, which means before Wed for me.

**Comment by xylar** [comment]
Okay, I'll merge #485 as soon as we're confident there aren't any remaining bits of clean-up.

@milenaveneziani, could you let me know when you're sure `diagnostics` is up-to-date on all supported machines?

**Comment by xylar** [comment]
Okay, are we ready to create the v1.1 tag and build the v1.1 package?!

**Comment by milenaveneziani** [comment]
yep, I think so.

**Comment by milenaveneziani** [comment]
@xylar: one last question: is this part about Installation in the documentation up to date:
https://mpas-analysis.readthedocs.io/en/master/quick_start.html#installation

**Comment by xylar** [comment]
That part will update when we create v1.1.  It is updated here:
https://mpas-analysis.readthedocs.io/en/latest/quick_start.html

I will need to create the package and upload it to the e3sm channel, which I will do right after creating v1.1. 

Let me know if you see any issues.
